from flask import Flask, request, jsonify, Response
from flask_cors import CORS
from flask_compress import Compress
import numpy as np
import geopandas as gpd
import pandas as pd
import os
import re
from pathlib import Path
from dotenv import load_dotenv
from supabase import create_client

_ROOT = Path(__file__).resolve().parent.parent

app = Flask(__name__)
Compress(app)
CORS(app, origins=[
    "https://tinyhomeproject.netlify.app",
    "http://localhost:5173",
])

# Load environment variables
load_dotenv()

# Supabase setup
supabase_url = os.getenv("SUPABASE_URL")
supabase_key = os.getenv("SUPABASE_KEY")
supabase = create_client(supabase_url, supabase_key) if supabase_url and supabase_key else None

def parse_support(val):
    """Strictly interpret a vote's support value. Returns True/False, or None if invalid.
    Guards against Python's bool() coercion (bool("false") is True), which would silently
    record opposition as support and corrupt the research dataset."""
    if isinstance(val, bool):
        return val
    if isinstance(val, (int, float)) and val in (0, 1):
        return bool(val)
    if isinstance(val, str):
        s = val.strip().lower()
        if s in ("true", "yes", "1"):
            return True
        if s in ("false", "no", "0"):
            return False
    return None


# Map UI labels to GeoJSON columns
feature_map = {
    "Transit Access": "transit_dist",
    "Affordable Housing": "public_housing_dist",
    "Water Infrastructure": "water_infrastructure_dist",
    "Urban Plan Priority Area": "general_plan_dist"
}
features = list(feature_map.keys())
score_cols = list(feature_map.values())

# ── Load GeoJSON once at startup and pre-compute lat/lon ──
print("Loading GeoJSON data...")
_gdf = gpd.read_file(_ROOT / "data" / "candidates" / "candidates_with_features.geojson").to_crs(epsg=4326)
_utm = _gdf.to_crs(26910)
_cent_ll = gpd.GeoSeries(_utm.geometry.centroid, crs=26910).to_crs(4326)
_gdf["lon"] = _cent_ll.x
_gdf["lat"] = _cent_ll.y
CACHED_GDF = _gdf
del _utm, _cent_ll

def min_max_normalize(series: pd.Series) -> pd.Series:
    s = pd.to_numeric(series, errors="coerce")
    if s.notna().sum() == 0:
        return pd.Series(np.zeros(len(s)), index=s.index)
    s = s.fillna(s.max())
    vmin, vmax = float(s.min()), float(s.max())
    if vmax == vmin:
        return pd.Series(np.zeros(len(s)), index=s.index)
    return (s - vmin) / (vmax - vmin)

# Pre-normalize the distance columns
CACHED_NORM = {col: min_max_normalize(CACHED_GDF[col]) for col in score_cols}
print(f"Loaded {len(CACHED_GDF)} candidate sites.")

# ── Load polygon parking data (generated by generate_parking_polygons.py) ──
_POLYGON_FILE = _ROOT / "data" / "polygons" / "parking_polygons_latest.geojson"
_poly_total = 0
try:
    with open(_POLYGON_FILE, encoding="utf-8") as _f:
        POLY_RAW = _f.read().replace(':NaN', ':null').replace(': NaN', ': null')
    _m = re.search(r'"total_spots":(\d+)', POLY_RAW)
    _poly_total = int(_m.group(1)) if _m else 0
    print(f"Loaded parking polygons ({_poly_total:,} spots).")
except Exception as _e:
    print(f"Warning: parking_polygons_latest.geojson not found ({_e}). Run generate_parking_polygons.py first.")
    POLY_RAW = '{"type":"FeatureCollection","total_spots":0,"features":[]}'
    _poly_total = 0

# Content-hash ETag so browsers cache this 52 MB payload and revalidate cheaply (304) on
# each page load instead of re-downloading + re-gzipping it every time. The hash changes
# only when the polygon data changes (a new pipeline run + deploy), forcing a fresh fetch.
import hashlib
POLY_ETAG = 'W/"' + hashlib.md5(POLY_RAW.encode("utf-8")).hexdigest() + '"'

@app.route("/api/ahp", methods=["POST"])
def calculate_ahp():
    data = request.get_json(silent=True) or {}
    comparisons = data.get("comparisons", {})
    size = len(features)
    ahp_matrix = np.ones((size, size))

    # Build pairwise comparison matrix
    for i, f1 in enumerate(features):
        for j, f2 in enumerate(features):
            if i >= j:
                continue
            key = f"{f1}__vs__{f2}"
            val = comparisons.get(key, "Equal")
            scale = {
                f"{f1} much more": 5,
                f"{f1} more": 3,
                "Equal": 1,
                f"{f2} more": 1/3,
                f"{f2} much more": 1/5,
            }.get(val, 1)
            ahp_matrix[i, j] = scale
            ahp_matrix[j, i] = 1/scale

    # Principal eigenvector weights + consistency
    eigvals, eigvecs = np.linalg.eig(ahp_matrix)
    imax = np.argmax(eigvals.real)
    w = np.abs(eigvecs[:, imax].real)
    w = w / w.sum()

    RI = {1:0,2:0,3:0.58,4:0.90,5:1.12,6:1.24,7:1.32,8:1.41,9:1.45,10:1.49}
    n = len(features)
    lambda_max = float(eigvals.real[imax])
    CI = (lambda_max - n) / (n - 1) if n > 1 else 0.0
    CR = CI / RI.get(n, 1.49) if n in RI else None

    weights_for_calc = { feature_map[features[i]]: float(w[i]) for i in range(n) }
    display_weights  = { k: round(v, 4) for k, v in weights_for_calc.items() }

    gdf = CACHED_GDF.copy()
    norm_scores = [CACHED_NORM[col] for col in score_cols]

    weight_array = np.array([weights_for_calc.get(col, 0.0) for col in score_cols])
    weight_array = weight_array / weight_array.sum()
    gdf["final_score"] = sum(wi * si for wi, si in zip(weight_array, norm_scores))

    ranked = gdf.sort_values("final_score", ascending=True).reset_index(drop=True)
    ranked["rank"] = ranked.index + 1

    top_sites = ranked.head(500)[["lat", "lon", "rank", "final_score"]].to_dict(orient="records")

    return jsonify({
        "weights": display_weights,
        "top_sites": top_sites,
        "consistency": {
            "lambda_max": round(lambda_max, 6),
            "CI": round(CI, 6),
            "CR": round(CR, 6) if CR is not None else None
        }
    })

@app.route("/api/default_map", methods=["GET"])
def default_map():
    cols = ["lat", "lon", "id", "address", "transit_dist",
            "water_infrastructure_dist", "city_facility_dist",
            "homeless_service_dist"]
    subset = CACHED_GDF[cols].copy()
    subset["id"] = subset["id"].astype(str)
    sites = subset.to_dict(orient="records")
    return jsonify({"sites": sites})

@app.route("/api/votes/summary", methods=["GET"])
def get_votes_summary():
    if not supabase:
        return jsonify({"total_yes": 0}), 200
    try:
        # count="exact" returns the true total without the default 1,000-row page cap
        result = supabase.table("votes").select("id", count="exact").eq("support", True).execute()
        return jsonify({"total_yes": result.count or 0}), 200
    except Exception as e:
        print(f"Error fetching vote summary: {e}")
        return jsonify({"total_yes": 0}), 200

@app.route("/api/votes", methods=["GET"])
def get_votes():
    if not supabase:
        return jsonify({}), 200
    try:
        # Read pre-aggregated per-site tallies from the site_vote_summary view instead of
        # re-tallying every raw vote row in Python on each request. The DB does the GROUP BY,
        # and we ship one row per *voted* site rather than one per vote — this scales with the
        # number of voted sites (bounded), not the ever-growing total vote count.
        # The view LEFT JOINs all sites, so filter to voted ones; still paginate for the cap.
        counts = {}
        page = 0
        PAGE = 1000
        while True:
            start = page * PAGE
            result = (
                supabase.table("site_vote_summary")
                .select("site_id, support_count, oppose_count, total_votes")
                .gt("total_votes", 0)
                .range(start, start + PAGE - 1)
                .execute()
            )
            rows = result.data or []
            for row in rows:
                counts[row["site_id"]] = {
                    "yes": row.get("support_count") or 0,
                    "no": row.get("oppose_count") or 0,
                    "total": row.get("total_votes") or 0,
                }
            if len(rows) < PAGE:
                break
            page += 1
        return jsonify(counts), 200
    except Exception as e:
        print(f"Error fetching votes: {e}")
        return jsonify({}), 200

@app.route("/api/votes/mine", methods=["GET"])
def get_my_votes():
    """Return {site_id: support_bool} for one user so their votes rehydrate on any
    device (the DB is the source of truth; localStorage is only a client-side cache)."""
    if not supabase:
        return jsonify({}), 200
    user_id = (request.args.get("user_id") or "").strip()
    if not user_id:
        return jsonify({"error": "user_id is required"}), 400
    try:
        # Paginate: PostgREST caps at 1,000 rows/query and one user may have more
        # (batch voting can select thousands of spots at once).
        mine = {}
        page = 0
        PAGE = 1000
        while True:
            start = page * PAGE
            result = (
                supabase.table("votes")
                .select("site_id, support")
                .eq("user_id", user_id)
                .range(start, start + PAGE - 1)
                .execute()
            )
            rows = result.data or []
            for row in rows:
                mine[row["site_id"]] = row["support"]
            if len(rows) < PAGE:
                break
            page += 1
        return jsonify(mine), 200
    except Exception as e:
        print(f"Error fetching user's votes: {e}")
        return jsonify({}), 200

@app.route("/api/votes", methods=["POST"])
def submit_vote():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    data = request.get_json(silent=True) or {}
    site_id = str(data.get("site_id", "")).strip()
    support = parse_support(data.get("support"))
    comment = (data.get("comment") or "")[:500]
    user_id = data.get("user_id") or None
    if not site_id or support is None:
        return jsonify({"error": "site_id and a boolean support are required"}), 400
    # Voting requires login: every vote must be attributable to a user so it can be
    # joined to that respondent's profile for research.
    if not user_id:
        return jsonify({"error": "You must be logged in to vote"}), 401
    try:
        row = {"site_id": site_id, "support": support,
               "comment": comment or None, "user_id": str(user_id)}
        supabase.table("votes").upsert(row, on_conflict="user_id,site_id").execute()
        return jsonify({"status": "ok"}), 201
    except Exception as e:
        print(f"Error saving vote: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

@app.route("/api/votes", methods=["DELETE"])
def delete_vote():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    data = request.get_json(silent=True) or {}
    site_id = str(data.get("site_id", "")).strip()
    user_id = str(data.get("user_id", "")).strip()
    if not site_id or not user_id:
        return jsonify({"error": "site_id and user_id are required"}), 400
    try:
        supabase.table("votes").delete().eq("site_id", site_id).eq("user_id", user_id).execute()
        return jsonify({"status": "ok"}), 200
    except Exception as e:
        print(f"Error deleting vote: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

@app.route("/api/votes/batch", methods=["POST"])
def submit_votes_batch():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    data = request.get_json(silent=True) or {}
    site_ids = data.get("site_ids", [])
    support = parse_support(data.get("support"))
    comment = (data.get("comment") or "")[:500]
    user_id = data.get("user_id") or None
    if not site_ids or support is None:
        return jsonify({"error": "site_ids and a boolean support are required"}), 400
    if len(site_ids) > 500:
        return jsonify({"error": "Too many site_ids (max 500)"}), 400
    # Voting requires login (see submit_vote).
    if not user_id:
        return jsonify({"error": "You must be logged in to vote"}), 401
    try:
        rows = [{"site_id": str(sid), "support": support,
                 "comment": comment or None, "user_id": str(user_id)} for sid in site_ids]
        supabase.table("votes").upsert(rows, on_conflict="user_id,site_id").execute()
        return jsonify({"status": "ok", "count": len(rows)}), 201
    except Exception as e:
        print(f"Error saving batch votes: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

@app.route("/api/votes/batch", methods=["DELETE"])
def delete_votes_batch():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    data = request.get_json(silent=True) or {}
    site_ids = data.get("site_ids", [])
    user_id = str(data.get("user_id", "")).strip()
    if not site_ids or not user_id:
        return jsonify({"error": "site_ids and user_id are required"}), 400
    if len(site_ids) > 500:
        return jsonify({"error": "Too many site_ids (max 500)"}), 400
    try:
        supabase.table("votes").delete().in_("site_id", [str(s) for s in site_ids]).eq("user_id", user_id).execute()
        return jsonify({"status": "ok", "count": len(site_ids)}), 200
    except Exception as e:
        print(f"Error deleting batch votes: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

@app.route("/api/wsm", methods=["POST"])
def weighted_sum_model():
    data = request.get_json(silent=True) or {}
    weights = data.get("weights", {}) or {}

    gdf = CACHED_GDF.copy()

    cols = [c for c in weights.keys() if c in gdf.columns]
    if not cols:
        return jsonify({"error": "No valid weight columns provided"}), 400

    wvals = np.array([float(weights[c]) for c in cols], dtype=float)
    if wvals.sum() < 1e-9:
        return jsonify({"error": "All weights are zero"}), 400
    wvals = wvals / wvals.sum()

    norm_scores = [CACHED_NORM.get(c, min_max_normalize(gdf[c])) for c in cols]
    gdf["final_score"] = sum(w * s for w, s in zip(wvals, norm_scores))

    ranked = gdf.sort_values("final_score", ascending=True).reset_index(drop=True)
    ranked["rank"] = ranked.index + 1

    top_sites = ranked.head(500)[["lat", "lon", "rank", "final_score"]].to_dict(orient="records")
    display_weights = { cols[i]: round(float(wvals[i]), 4) for i in range(len(cols)) }

    return jsonify({"weights": display_weights, "top_sites": top_sites})

@app.route("/api/polygon_map", methods=["GET"])
def polygon_map():
    # Cheap revalidation: if the client already has this exact payload, return 304 (no body),
    # skipping the 52 MB send + gzip entirely.
    if request.headers.get("If-None-Match") == POLY_ETAG:
        return Response(status=304, headers={"ETag": POLY_ETAG, "Cache-Control": "no-cache"})
    resp = Response(POLY_RAW, mimetype="application/json")
    resp.headers["ETag"] = POLY_ETAG
    resp.headers["Cache-Control"] = "no-cache"   # cache, but always revalidate via ETag
    return resp

@app.route("/api/polygon_count", methods=["GET"])
def polygon_count():
    return jsonify({"total_spots": _poly_total})

@app.route("/healthz")
def healthz():
    return "OK", 200

@app.route('/api/save_ahp_submission', methods=['POST'])
def save_ahp_submission():
    if not supabase:
        return {'error': 'Database not configured'}, 500

    data = request.get_json(silent=True) or {}
    try:
        # Prepare the submission data
        submission = {
            'name': data.get('name'),
            'occupation': data.get('occupation'),
            'location': data.get('location'),
            'feedback': data.get('feedback'),
            'method': data.get('method', 'AHP'),
            'consistency_ratio': data.get('consistency_ratio'),
            'weights': data.get('weights', {}),
            'top_sites': (data.get('top_sites') or [])[:300],  # Limit to 300 sites
        }

        # Insert into Supabase
        result = supabase.table('submissions').insert(submission).execute()

        return {'status': 'success'}, 200
    except Exception as e:
        print(f"Error saving to Supabase: {e}")
        return {'error': 'Something went wrong. Please try again.'}, 500

@app.route("/api/ping", methods=["GET"])
def ping():
    """Keepalive endpoint — touches Supabase so the project doesn't pause."""
    if supabase:
        try:
            supabase.table("votes").select("id").limit(1).execute()
        except Exception:
            pass
    return jsonify({"status": "ok"}), 200

@app.route("/api/suggestions", methods=["GET"])
def get_suggestions():
    if not supabase:
        return jsonify([]), 200
    try:
        result = supabase.table("suggestions").select("*").execute()
        return jsonify(result.data), 200
    except Exception as e:
        print(f"Error fetching suggestions: {e}")
        return jsonify([]), 200

@app.route("/api/suggestions", methods=["POST"])
def submit_suggestion():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    data = request.get_json(silent=True) or {}
    try:
        supabase.table("suggestions").insert({
            "lat": float(data["lat"]),
            "lng": float(data["lng"]),
            "name": (data.get("name") or "")[:200] or None,
            "occupation": (data.get("occupation") or "")[:200] or None,
            "reason": (data.get("reason") or "")[:500] or None,
        }).execute()
        return jsonify({"status": "ok"}), 201
    except Exception as e:
        print(f"Error saving suggestion: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)
